### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by izcream**

### CODE REVIEW

**Comment by emailnitram** [comment]
@izcream would you like to help maintain and improve this repo?

**Comment by izcream** [comment]
What should i do😅. If i can help i will. You try to make dictionary site right?

**Comment by emailnitram** [comment]
image
Right now this app is just to help people who want to learn how to type in Thai practice their typing skills.  For now there is a set of words that are random.  To improve this, categories could be added or sentences.

**Review by emailnitram — APPROVED** [review]

**Comment by izcream** [comment]
I will help you added/fixed some spell wrong word in json when im free😀

**Pull request merged**
